### ISSUE TITLE
Extend UPS/Rate, change private method to protected

### ISSUE THREAD

**Issue by dranzd** [pdt256/shipping#15]
This class [pdt256\Shipping\UPS\Rate](https://github.com/pdt256/shipping/blob/master/src/UPS/Rate.php#L182) is allowed to be extended.  But one of its method getPackagesXmlString is private.  Should this method be protected so that it can overriden?

I'm using this package and there's a need for me to send a different rate request configuration.  I"ve extended the said class but I needed to create another method just for the same purpose as getPackagesXmlString.  It would be nice if this method be changed from private to protected so there's no need to create another method name in case the method needs to be overriden.

If this can be done, I'll be happy to send a PR.

**Comment by pdt256** [comment]
No need for a PR. Already done.
