### ISSUE TITLE
Unable to show shipping information 

### ISSUE THREAD

**Issue by ZaheerAbbasAghani** [pdt256/shipping#17]
I had used below code in my controller getting error
Error:
FatalThrowableError in CheckoutController.php line 30:
Class 'App\Http\Controllers\Shipment' not found

Code : 
$shipment = new Shipment;
$shipment
    ->setFromIsResidential(false)
    ->setFromStateProvinceCode('IN')
    ->setFromPostalCode('46205')
    ->setFromCountryCode('US')
    ->setToIsResidential(true)
    ->setToPostalCode('20101')
    ->setToCountryCode('US');

$package = new Package;
$package
    ->setLength(12)
    ->setWidth(4)
    ->setHeight(3)
    ->setWeight(3);

$shipment->addPackage($package);

$fedex = new Fedex\Rate([
    'prod'           => FALSE,
    'key'            => 'XXXX',
    'password'       => 'XXXX',
    'accountNumber' => 'XXXX',
    'meterNumber'   => 'XXXX',
    'dropOffType'  => 'BUSINESS_SERVICE_CENTER',
    'shipment'       => $shipment,
    'approvedCodes'  => [
        'FEDEX_EXPRESS_SAVER',  // 1-3 business days
        'FEDEX_GROUND',         // 1-5 business days
        'GROUND_HOME_DELIVERY', // 1-5 business days
        'FEDEX_2_DAY',          // 2 business days
        'STANDARD_OVERNIGHT',   // overnight
    ],
    'requestAdapter' => new RateRequest\StubFedex(),
]);

$rates = $fedex->getRates();

**Comment by pdt256** [comment]
This is a PHP namespace issue.

Did you install via composer?
Is the composer autoloader being included in your application bootstrap?
Did you include `use pdt256\Shipping\Shipment;` in files referencing the `Shipment` object?
